# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Déclenche le workflow lors d'un push sur la branche principale
  pull_request:
    branches:
      - main  # Déclenche le workflow lors d'une pull request vers la branche principale

jobs:
  run-makefile:
    runs-on: ubuntu-latest  # Utilise une machine virtuelle Ubuntu

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Utilisez la version de Python de votre projet

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Exécuter les étapes du Makefile
      - name: Run Makefile steps
        run: |
          make prepare
          make train
          make test
